# set true collor
set-option -sa terminal-overrides ",xterm*:Tc"

# prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse on

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# set vi-mode
set-window-option -g mode-keys vi

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


# status bar
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-plugins 'git cpu-usage ram-usage time date'
set -g @dracula-cpu-display-load false
set -g @dracula-show-empty-plugins false

set -g status-position top

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# plugins
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
