
# theme = "base16_transparent"
theme = "dark_plus"

[editor]
true-color = true
line-number = "relative"


[keys.normal.space]
w = ":write"
q = ":quit"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.gutters.line-numbers]
min-width = 50
